# (C) Copyright 2022-2022 UCAR
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# AWS CodeBuild spec file for the JTD Frontend docker image
#-------------------------------------------------------------------------------

version: 0.2

phases:
  # install:
  pre_build:
    commands:
    - aws --version
    - docker version
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:=latest}
    - >
      aws ecr get-login-password --region $AWS_DEFAULT_REGION
      | docker login --username AWS --password-stdin ${REPOSITORY_URI%/*}
    - docker pull $REPOSITORY_URI:latest || true
    - cd frontend

  build:
    commands:
    - docker build --cache-from $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG .
    - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - docker push $REPOSITORY_URI:latest
    - >
      printf '[{"name":"frontend_build","imageUri":"%s"}]'
      $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json